# source 'https://rubygems.org'
# gem 'jekyll', '<4'
# gem 'jekyll-archives'
# gem 'jekyll-sitemap'
# gem 'jekyll-paginate-v2'
source "https://rubygems.org"

gem "jekyll", "~>2.5"
gem "jekyll-archives", "~>2.0"
gem "jekyll-sitemap", "~>0.8"